name: fit_wallet
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  go_router: ^10.1.0
  flutter_riverpod: ^2.3.7
  dio: ^5.3.2
  uuid: ^3.0.7
  localstorage: ^4.0.1+4
  formz: ^0.6.0
  intl: any
  font_awesome_flutter: ^10.5.0
  sqflite: ^2.3.0
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/data/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
